name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']  # Only Ruby 3.2
        appraisal: ['rails-7.2', 'rails-8-sprockets', 'rails-8-propshaft']
      fail-fast: true  # Stop on first failure
    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.appraisal }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.appraisal }}-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Install appraisals
        run: bundle exec appraisal install
      - name: Migrate test database
        run: |
          mkdir -p test/dummy/db
          ln -sf ../../db/gaggle_migrate test/dummy/db/migrate  # Adjust if path differs
          bundle exec appraisal ${{ matrix.appraisal }} rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} bin/test --verbose